import Alert from "@/components/Alert";
import { useToggle } from "@/components/utils";
import Head from "next/head";
import { useEffect } from "react";
import * as Icons from "react-bootstrap-icons";

const DefaultHead = () => (
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

const Container = ({ children }) => (
  <main className="grid gap-4 p-4 bg-gray-400">{children}</main>
);

const Row = ({ children }) => (
  <div className="flex justify-center items-center">{children}</div>
);

export default function Home() {
  return (
    <>
      <DefaultHead />
      <Container>
        <Row>
          <Alert
            className="bg-yellow-500 text-white"
            icon={<Icons.InfoCircle className="fill-white" size={18} />}
            actionButton={<button>Update</button>}
            closeButton={
              <button className="flex justify-center items-center">
                <Icons.XCircle size={18} />
              </button>
            }
          >
            New software update available.
          </Alert>
        </Row>
      </Container>
    </>
  );
}
